version: "3.5"
services:
  provider-1:
    build:
      context: .
      dockerfile: Provider.Dockerfile
    image: provider:latest
    restart: always
    deploy:
      replicas: 6
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/.local/share/yagna/
    devices:
      - /dev/kvm:/dev/kvm
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:7465 | grep -q 401"]
      interval: 10s
      timeout: 5s
      retries: 1
      start_period: 40s
    environment:
      - NODE_NAME=provider-1
      - SUBNET=${YAGNA_SUBNET:-golemjstest}
